<?php /* Application: wordpress */

 header("Location: /blog/");

 // Questo file e' stato autogenerato da AlterVista 
 // Modificate o sostituite questo file solo se siete certi di quello che fate!
 //  Per proteggere questo file, disabilitando le funzioni che lo modificano automaticamente,
 // potete eliminare il commento sulla prima riga (tutto cio' che c'e' tra /* e */)
 //
 // This file was autogenerated by AlterVista
 // Modify or substitute this file only if you know what are you doing!
 //  To protect this file, disabling AlterVista's automated functions that edit it from control panel,
 // you can remove the comment on the first row of this file (everything from /* and */)
?>
